driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[berkshelf-api-server]
    attributes: { berkshelf_api: { release: "v2.1.1" } }
